services:
  spring-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-app
    command: mvn spring-boot:run
    ports:
      - "7200:7200"
    volumes:
      - $HOME/.aws/:/home/app/.aws/:ro
    networks:
      - my_network

  angular-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "80:80"
    depends_on:
      - spring-app
    networks:
      - my_network
    command: /bin/sh -c "while ! nc -z spring-app 7200; do sleep 3; done && ng build --prod"

networks:
  my_network:
    driver: bridge