drop table listing;
drop table "user";
CREATE SEQUENCE IF NOT EXISTS listing_id_seq INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_id_seq INCREMENT BY 1;

CREATE TABLE listing
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    description  VARCHAR(255),
    price        INTEGER                                 NOT NULL,
    user_id      BIGINT,
    image_url    VARCHAR(255),
    pub_date     TIMESTAMP WITHOUT TIME ZONE,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_listing PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE listing
    ADD CONSTRAINT fk_listing_on_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE NO ACTION;